### ISSUE TITLE
Dependancies not installed

### ISSUE THREAD

**Issue by johnthagen** [ollix/cclint#1]
When I do:

`pip install cclint`

The dependencies `cpplint` and `colorama` are not also automatically installed.

**Comment by johnthagen** [comment]
@theandrewdavis thanks for the PR's to fix some issues!
@olliwang, would it be possible to get a new release for PyPI with these latest changes?  Thanks!

**Comment by olliwang** [comment]
I've uploaded a new version (0.2) to PyPI with the latest changes. However, as the `install_requires` keyword is only supported by `setuptools`, I'm not sure if `pip` can install it without `setuptools` installed.

**Comment by johnthagen** [comment]
@olliwang Isn't `setuptools` bundled with `pip` for any modern install of Python?

Anyway @theandrewdavis's fix solved this problem at least on Windows with Python 3.5
